
services:
  bas-database-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  bas-nginx:
    image: nginx:latest
    container_name: bas-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/example.com.conf:/etc/nginx/conf.d/default.conf
  bas-php-fpm:
    build: ./docker/php/
    container_name: bas-php-fpm
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
volumes:
  database_data:




