
services:
###> doctrine/doctrine-bundle ###
  bas-database:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: bas-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432

  bas-nginx:
    image: nginx:latest
    container_name: bas-nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/example.com.conf:/etc/nginx/conf.d/default.conf
  bas-php-fpm:
    build: ./docker/php/
    container_name: bas-php-fpm
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
volumes:
  database_data:




